#!/usr/bin/env ruby

require 'erb'
require 'json'

def run_commands(file, output)
  ref_rd, ref_wr = IO.pipe
  decode_pid = Process.spawn("ffmpeg -i #{file} -stats -pix_fmt yuv444p -f yuv4mpegpipe -", :out => ref_wr, :close_others => true)
  ref_wr.close

  cat_pid = Process.spawn("cat", :in => ref_rd, :out => output, :close_others => true)
  ref_rd.close

  Process.waitpid decode_pid
  Process.waitpid cat_pid
end

class Template
  COUNT = 180
  def psnr_data
    data = []
    1.upto(COUNT) do |x|
      data << {:x => x, :y => rand}
    end
    data
  end

  def ssim_data
    data = []
    1.upto(COUNT) do |x|
      data << {:x => x, :y => rand*2}
    end
    data
  end

  def render
    @psnr_data = JSON.dump(psnr_data)
    @ssim_data = JSON.dump(ssim_data)
    @keyframes = JSON.dump [
      1, 24, 58, 124, 311, 430, 791, 872
    ]

  end

  def get_binding
    binding
  end
end

renderer = Template.new
renderer.render
template_obj = ERB.new(File.new('views/index.html', 'r').read)

puts template_obj.result(renderer.get_binding)

reference = ARGV[0]
input = ARGV[1]

run_commands(reference, "reference.dat")
run_commands(input, "input.dat")

